version: '3.9'

services:
  asap-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asap-github
    ports:
      - "8021:5432"
    restart: unless-stopped