version: '3.9'

services:
  asap-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asap-github
    ports:
      - "7021:5432"
    restart: unless-stopped
    
  asap-redis:
    image: redis:latest
    restart: always
    ports:
      - '8023:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass asap-github-local-redis